compilers=&exo_1_0_0

defaultCompiler=exocc
supportsBinary=false
compilerType=exo
instructionSet=llvm

group.exo_1_0_0.compilers=exocc
compiler.exocc.exe=/home/ubuntu/exo/exo/bin/exocc
compiler.exocc.name=exocc
